// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "SurfaceMesh_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// alphaWrapPoints_cpp
Rcpp::List alphaWrapPoints_cpp(const Rcpp::NumericMatrix pts, const double alpha_rel, const double offset_rel, const bool normals);
RcppExport SEXP _SurfaceMesh_alphaWrapPoints_cpp(SEXP ptsSEXP, SEXP alpha_relSEXP, SEXP offset_relSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_rel(alpha_relSEXP);
    Rcpp::traits::input_parameter< const double >::type offset_rel(offset_relSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(alphaWrapPoints_cpp(pts, alpha_rel, offset_rel, normals));
    return rcpp_result_gen;
END_RCPP
}
// alphaWrapMesh_cpp
Rcpp::List alphaWrapMesh_cpp(const Rcpp::List rmesh, const double alpha_rel, const double offset_rel, const bool normals);
RcppExport SEXP _SurfaceMesh_alphaWrapMesh_cpp(SEXP rmeshSEXP, SEXP alpha_relSEXP, SEXP offset_relSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_rel(alpha_relSEXP);
    Rcpp::traits::input_parameter< const double >::type offset_rel(offset_relSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(alphaWrapMesh_cpp(rmesh, alpha_rel, offset_rel, normals));
    return rcpp_result_gen;
END_RCPP
}
// boolIntersectionEK_cpp
Rcpp::List boolIntersectionEK_cpp(const Rcpp::List rmeshes, const bool repairSoup, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_boolIntersectionEK_cpp(SEXP rmeshesSEXP, SEXP repairSoupSEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshes(rmeshesSEXP);
    Rcpp::traits::input_parameter< const bool >::type repairSoup(repairSoupSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(boolIntersectionEK_cpp(rmeshes, repairSoup, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// boolDifferenceEK_cpp
Rcpp::List boolDifferenceEK_cpp(const Rcpp::List rmesh1, const Rcpp::List rmesh2, const bool repairSoup, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_boolDifferenceEK_cpp(SEXP rmesh1SEXP, SEXP rmesh2SEXP, SEXP repairSoupSEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh1(rmesh1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh2(rmesh2SEXP);
    Rcpp::traits::input_parameter< const bool >::type repairSoup(repairSoupSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(boolDifferenceEK_cpp(rmesh1, rmesh2, repairSoup, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// boolUnionEK_cpp
Rcpp::List boolUnionEK_cpp(const Rcpp::List rmeshes, const bool repairSoup, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_boolUnionEK_cpp(SEXP rmeshesSEXP, SEXP repairSoupSEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshes(rmeshesSEXP);
    Rcpp::traits::input_parameter< const bool >::type repairSoup(repairSoupSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(boolUnionEK_cpp(rmeshes, repairSoup, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// getJSCDSC_cpp
Rcpp::List getJSCDSC_cpp(const Rcpp::List rmeshes, const bool repairSoup, const bool verbose);
RcppExport SEXP _SurfaceMesh_getJSCDSC_cpp(SEXP rmeshesSEXP, SEXP repairSoupSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshes(rmeshesSEXP);
    Rcpp::traits::input_parameter< const bool >::type repairSoup(repairSoupSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(getJSCDSC_cpp(rmeshes, repairSoup, verbose));
    return rcpp_result_gen;
END_RCPP
}
// getHausdorffApprox_cpp
double getHausdorffApprox_cpp(const Rcpp::List rmesh1, const Rcpp::List rmesh2, const bool symmetric, const unsigned int n);
RcppExport SEXP _SurfaceMesh_getHausdorffApprox_cpp(SEXP rmesh1SEXP, SEXP rmesh2SEXP, SEXP symmetricSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh1(rmesh1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh2(rmesh2SEXP);
    Rcpp::traits::input_parameter< const bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(getHausdorffApprox_cpp(rmesh1, rmesh2, symmetric, n));
    return rcpp_result_gen;
END_RCPP
}
// getHausdorffEst_cpp
double getHausdorffEst_cpp(const Rcpp::List rmesh1, const Rcpp::List rmesh2, const bool symmetric, const double error_bound);
RcppExport SEXP _SurfaceMesh_getHausdorffEst_cpp(SEXP rmesh1SEXP, SEXP rmesh2SEXP, SEXP symmetricSEXP, SEXP error_boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh1(rmesh1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh2(rmesh2SEXP);
    Rcpp::traits::input_parameter< const bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< const double >::type error_bound(error_boundSEXP);
    rcpp_result_gen = Rcpp::wrap(getHausdorffEst_cpp(rmesh1, rmesh2, symmetric, error_bound));
    return rcpp_result_gen;
END_RCPP
}
// getSurfaceDist_cpp
Rcpp::List getSurfaceDist_cpp(const Rcpp::List rmesh1, const Rcpp::List rmesh2, const bool returnDists, const bool symmetric, const double p, const Rcpp::List ropts);
RcppExport SEXP _SurfaceMesh_getSurfaceDist_cpp(SEXP rmesh1SEXP, SEXP rmesh2SEXP, SEXP returnDistsSEXP, SEXP symmetricSEXP, SEXP pSEXP, SEXP roptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh1(rmesh1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh2(rmesh2SEXP);
    Rcpp::traits::input_parameter< const bool >::type returnDists(returnDistsSEXP);
    Rcpp::traits::input_parameter< const bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< const double >::type p(pSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type ropts(roptsSEXP);
    rcpp_result_gen = Rcpp::wrap(getSurfaceDist_cpp(rmesh1, rmesh2, returnDists, symmetric, p, ropts));
    return rcpp_result_gen;
END_RCPP
}
// makeMesh_cpp
Rcpp::List makeMesh_cpp(const Rcpp::List rmesh, const bool triangulate, const bool repairSoup, const bool removeIntersections, const int removeMethod, const bool fillHoles, const bool fairHole, const unsigned int maxNumHoles, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_makeMesh_cpp(SEXP rmeshSEXP, SEXP triangulateSEXP, SEXP repairSoupSEXP, SEXP removeIntersectionsSEXP, SEXP removeMethodSEXP, SEXP fillHolesSEXP, SEXP fairHoleSEXP, SEXP maxNumHolesSEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate(triangulateSEXP);
    Rcpp::traits::input_parameter< const bool >::type repairSoup(repairSoupSEXP);
    Rcpp::traits::input_parameter< const bool >::type removeIntersections(removeIntersectionsSEXP);
    Rcpp::traits::input_parameter< const int >::type removeMethod(removeMethodSEXP);
    Rcpp::traits::input_parameter< const bool >::type fillHoles(fillHolesSEXP);
    Rcpp::traits::input_parameter< const bool >::type fairHole(fairHoleSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type maxNumHoles(maxNumHolesSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(makeMesh_cpp(rmesh, triangulate, repairSoup, removeIntersections, removeMethod, fillHoles, fairHole, maxNumHoles, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// makeMeshFF_cpp
Rcpp::List makeMeshFF_cpp(const Rcpp::String filename, const bool triangulate, const bool repairSoup, const bool removeIntersections, const int removeMethod, const bool fillHoles, const bool fairHole, const unsigned int maxNumHoles, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_makeMeshFF_cpp(SEXP filenameSEXP, SEXP triangulateSEXP, SEXP repairSoupSEXP, SEXP removeIntersectionsSEXP, SEXP removeMethodSEXP, SEXP fillHolesSEXP, SEXP fairHoleSEXP, SEXP maxNumHolesSEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::String >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate(triangulateSEXP);
    Rcpp::traits::input_parameter< const bool >::type repairSoup(repairSoupSEXP);
    Rcpp::traits::input_parameter< const bool >::type removeIntersections(removeIntersectionsSEXP);
    Rcpp::traits::input_parameter< const int >::type removeMethod(removeMethodSEXP);
    Rcpp::traits::input_parameter< const bool >::type fillHoles(fillHolesSEXP);
    Rcpp::traits::input_parameter< const bool >::type fairHole(fairHoleSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type maxNumHoles(maxNumHolesSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(makeMeshFF_cpp(filename, triangulate, repairSoup, removeIntersections, removeMethod, fillHoles, fairHole, maxNumHoles, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// makeMeshValid_cpp
Rcpp::List makeMeshValid_cpp(const Rcpp::List rmesh, const bool soup, const bool triangulate, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_makeMeshValid_cpp(SEXP rmeshSEXP, SEXP soupSEXP, SEXP triangulateSEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const bool >::type soup(soupSEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate(triangulateSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(makeMeshValid_cpp(rmesh, soup, triangulate, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// makeMeshValidFF_cpp
Rcpp::List makeMeshValidFF_cpp(const Rcpp::String filename, const bool soup, const bool triangulate, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_makeMeshValidFF_cpp(SEXP filenameSEXP, SEXP soupSEXP, SEXP triangulateSEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::String >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const bool >::type soup(soupSEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate(triangulateSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(makeMeshValidFF_cpp(filename, soup, triangulate, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// addVNormals_cpp
Rcpp::List addVNormals_cpp(const Rcpp::List rmesh);
RcppExport SEXP _SurfaceMesh_addVNormals_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(addVNormals_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// doesBoundVolume_cpp
bool doesBoundVolume_cpp(const Rcpp::List rmesh);
RcppExport SEXP _SurfaceMesh_doesBoundVolume_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(doesBoundVolume_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// doesSelfIntersect_cpp
bool doesSelfIntersect_cpp(const Rcpp::List rmesh);
RcppExport SEXP _SurfaceMesh_doesSelfIntersect_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(doesSelfIntersect_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// fillBoundaryHoles_cpp
Rcpp::List fillBoundaryHoles_cpp(const Rcpp::List rmesh, const bool fairHole, const unsigned int maxNumHoles, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_fillBoundaryHoles_cpp(SEXP rmeshSEXP, SEXP fairHoleSEXP, SEXP maxNumHolesSEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const bool >::type fairHole(fairHoleSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type maxNumHoles(maxNumHolesSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(fillBoundaryHoles_cpp(rmesh, fairHole, maxNumHoles, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// getArea_cpp
double getArea_cpp(const Rcpp::List rmesh);
RcppExport SEXP _SurfaceMesh_getArea_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(getArea_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// getBoundingBox_cpp
Rcpp::List getBoundingBox_cpp(const Rcpp::List rmesh);
RcppExport SEXP _SurfaceMesh_getBoundingBox_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(getBoundingBox_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// getBoundingBoxOptimal_cpp
Rcpp::List getBoundingBoxOptimal_cpp(const Rcpp::List rmeshIn, const bool triangulate, const bool normals);
RcppExport SEXP _SurfaceMesh_getBoundingBoxOptimal_cpp(SEXP rmeshInSEXP, SEXP triangulateSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshIn(rmeshInSEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate(triangulateSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(getBoundingBoxOptimal_cpp(rmeshIn, triangulate, normals));
    return rcpp_result_gen;
END_RCPP
}
// getCentroid_cpp
Rcpp::NumericVector getCentroid_cpp(const Rcpp::List rmesh);
RcppExport SEXP _SurfaceMesh_getCentroid_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(getCentroid_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// getConvexHull_cpp
Rcpp::List getConvexHull_cpp(const Rcpp::NumericMatrix rpoints, const bool normals);
RcppExport SEXP _SurfaceMesh_getConvexHull_cpp(SEXP rpointsSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type rpoints(rpointsSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(getConvexHull_cpp(rpoints, normals));
    return rcpp_result_gen;
END_RCPP
}
// getDistance_cpp
Rcpp::NumericVector getDistance_cpp(const Rcpp::List rmesh, const Rcpp::NumericMatrix rpoints);
RcppExport SEXP _SurfaceMesh_getDistance_cpp(SEXP rmeshSEXP, SEXP rpointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type rpoints(rpointsSEXP);
    rcpp_result_gen = Rcpp::wrap(getDistance_cpp(rmesh, rpoints));
    return rcpp_result_gen;
END_RCPP
}
// getVolume_cpp
double getVolume_cpp(const Rcpp::List rmesh);
RcppExport SEXP _SurfaceMesh_getVolume_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(getVolume_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// hasGarbage_cpp
bool hasGarbage_cpp(const Rcpp::List rmesh);
RcppExport SEXP _SurfaceMesh_hasGarbage_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(hasGarbage_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// isClosed_cpp
bool isClosed_cpp(const Rcpp::List rmesh);
RcppExport SEXP _SurfaceMesh_isClosed_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(isClosed_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// isValid_cpp
bool isValid_cpp(const Rcpp::List rmesh);
RcppExport SEXP _SurfaceMesh_isValid_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(isValid_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// orientToBoundVolume_cpp
Rcpp::List orientToBoundVolume_cpp(const Rcpp::List rmesh, const bool normals);
RcppExport SEXP _SurfaceMesh_orientToBoundVolume_cpp(SEXP rmeshSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(orientToBoundVolume_cpp(rmesh, normals));
    return rcpp_result_gen;
END_RCPP
}
// removeSelfIntersections_cpp
Rcpp::List removeSelfIntersections_cpp(const Rcpp::List rmesh, const int method, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_removeSelfIntersections_cpp(SEXP rmeshSEXP, SEXP methodSEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(removeSelfIntersections_cpp(rmesh, method, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// samplePoints_cpp
Rcpp::NumericMatrix samplePoints_cpp(const Rcpp::List rmesh, const Rcpp::List ropts);
RcppExport SEXP _SurfaceMesh_samplePoints_cpp(SEXP rmeshSEXP, SEXP roptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type ropts(roptsSEXP);
    rcpp_result_gen = Rcpp::wrap(samplePoints_cpp(rmesh, ropts));
    return rcpp_result_gen;
END_RCPP
}
// triangulateMesh_cpp
Rcpp::List triangulateMesh_cpp(const Rcpp::List rmesh, const bool normals);
RcppExport SEXP _SurfaceMesh_triangulateMesh_cpp(SEXP rmeshSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(triangulateMesh_cpp(rmesh, normals));
    return rcpp_result_gen;
END_RCPP
}
// jet_pca_normals_cpp
Rcpp::NumericMatrix jet_pca_normals_cpp(const Rcpp::NumericMatrix pts, const unsigned int nbNeighbors, const unsigned int method);
RcppExport SEXP _SurfaceMesh_jet_pca_normals_cpp(SEXP ptsSEXP, SEXP nbNeighborsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nbNeighbors(nbNeighborsSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(jet_pca_normals_cpp(pts, nbNeighbors, method));
    return rcpp_result_gen;
END_RCPP
}
// readFileSoup_cpp
Rcpp::List readFileSoup_cpp(const std::string filename, const bool verbose);
RcppExport SEXP _SurfaceMesh_readFileSoup_cpp(SEXP filenameSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(readFileSoup_cpp(filename, verbose));
    return rcpp_result_gen;
END_RCPP
}
// readFileMesh_cpp
Rcpp::List readFileMesh_cpp(const std::string filename, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_readFileMesh_cpp(SEXP filenameSEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(readFileMesh_cpp(filename, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// writeFile_cpp
void writeFile_cpp(const std::string filename, const bool binary, const int precision, const Rcpp::NumericMatrix vertices, const Rcpp::List faceList);
RcppExport SEXP _SurfaceMesh_writeFile_cpp(SEXP filenameSEXP, SEXP binarySEXP, SEXP precisionSEXP, SEXP verticesSEXP, SEXP faceListSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const bool >::type binary(binarySEXP);
    Rcpp::traits::input_parameter< const int >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type faceList(faceListSEXP);
    writeFile_cpp(filename, binary, precision, vertices, faceList);
    return R_NilValue;
END_RCPP
}
// reconstructAFS_cpp
Rcpp::List reconstructAFS_cpp(const Rcpp::NumericMatrix pts, const int nNeighbors, const bool repairSoup, const bool normals);
RcppExport SEXP _SurfaceMesh_reconstructAFS_cpp(SEXP ptsSEXP, SEXP nNeighborsSEXP, SEXP repairSoupSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const int >::type nNeighbors(nNeighborsSEXP);
    Rcpp::traits::input_parameter< const bool >::type repairSoup(repairSoupSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(reconstructAFS_cpp(pts, nNeighbors, repairSoup, normals));
    return rcpp_result_gen;
END_RCPP
}
// reconstructPoisson_cpp
Rcpp::List reconstructPoisson_cpp(const Rcpp::NumericMatrix pts, const Rcpp::NumericMatrix normalsIn, const double spacing, const double smAngle, const double smRadius, const double smDistance, const bool normals);
RcppExport SEXP _SurfaceMesh_reconstructPoisson_cpp(SEXP ptsSEXP, SEXP normalsInSEXP, SEXP spacingSEXP, SEXP smAngleSEXP, SEXP smRadiusSEXP, SEXP smDistanceSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type normalsIn(normalsInSEXP);
    Rcpp::traits::input_parameter< const double >::type spacing(spacingSEXP);
    Rcpp::traits::input_parameter< const double >::type smAngle(smAngleSEXP);
    Rcpp::traits::input_parameter< const double >::type smRadius(smRadiusSEXP);
    Rcpp::traits::input_parameter< const double >::type smDistance(smDistanceSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(reconstructPoisson_cpp(pts, normalsIn, spacing, smAngle, smRadius, smDistance, normals));
    return rcpp_result_gen;
END_RCPP
}
// reconstructSSS_cpp
Rcpp::List reconstructSSS_cpp(const Rcpp::NumericMatrix pts, const int scaleIterations, const int nNeighbors, const int nSamples, const bool separateShells, const bool forceManifold, const double borderAngle, const bool repairSoup, const bool normals);
RcppExport SEXP _SurfaceMesh_reconstructSSS_cpp(SEXP ptsSEXP, SEXP scaleIterationsSEXP, SEXP nNeighborsSEXP, SEXP nSamplesSEXP, SEXP separateShellsSEXP, SEXP forceManifoldSEXP, SEXP borderAngleSEXP, SEXP repairSoupSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const int >::type scaleIterations(scaleIterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type nNeighbors(nNeighborsSEXP);
    Rcpp::traits::input_parameter< const int >::type nSamples(nSamplesSEXP);
    Rcpp::traits::input_parameter< const bool >::type separateShells(separateShellsSEXP);
    Rcpp::traits::input_parameter< const bool >::type forceManifold(forceManifoldSEXP);
    Rcpp::traits::input_parameter< const double >::type borderAngle(borderAngleSEXP);
    Rcpp::traits::input_parameter< const bool >::type repairSoup(repairSoupSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(reconstructSSS_cpp(pts, scaleIterations, nNeighbors, nSamples, separateShells, forceManifold, borderAngle, repairSoup, normals));
    return rcpp_result_gen;
END_RCPP
}
// remeshIsoUniform_cpp
Rcpp::List remeshIsoUniform_cpp(const Rcpp::List rmesh, const double targetEdgeLen, const unsigned int nIter, const unsigned int nRelaxSteps, const bool protectConstraints, const bool normals);
RcppExport SEXP _SurfaceMesh_remeshIsoUniform_cpp(SEXP rmeshSEXP, SEXP targetEdgeLenSEXP, SEXP nIterSEXP, SEXP nRelaxStepsSEXP, SEXP protectConstraintsSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const double >::type targetEdgeLen(targetEdgeLenSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nRelaxSteps(nRelaxStepsSEXP);
    Rcpp::traits::input_parameter< const bool >::type protectConstraints(protectConstraintsSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(remeshIsoUniform_cpp(rmesh, targetEdgeLen, nIter, nRelaxSteps, protectConstraints, normals));
    return rcpp_result_gen;
END_RCPP
}
// remeshIsoAdapt_cpp
Rcpp::List remeshIsoAdapt_cpp(const Rcpp::List rmesh, const double tol, const double edgeMin, const double edgeMax, const unsigned int nIter, const unsigned int nRelaxSteps, const bool protectConstraints, const bool normals);
RcppExport SEXP _SurfaceMesh_remeshIsoAdapt_cpp(SEXP rmeshSEXP, SEXP tolSEXP, SEXP edgeMinSEXP, SEXP edgeMaxSEXP, SEXP nIterSEXP, SEXP nRelaxStepsSEXP, SEXP protectConstraintsSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type edgeMin(edgeMinSEXP);
    Rcpp::traits::input_parameter< const double >::type edgeMax(edgeMaxSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nRelaxSteps(nRelaxStepsSEXP);
    Rcpp::traits::input_parameter< const bool >::type protectConstraints(protectConstraintsSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(remeshIsoAdapt_cpp(rmesh, tol, edgeMin, edgeMax, nIter, nRelaxSteps, protectConstraints, normals));
    return rcpp_result_gen;
END_RCPP
}
// simplifyLT_cpp
Rcpp::List simplifyLT_cpp(const Rcpp::List rmesh, const bool repairSoup, const bool repairMesh, const Rcpp::String method, const double ueRatio, const unsigned int ueCount, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_simplifyLT_cpp(SEXP rmeshSEXP, SEXP repairSoupSEXP, SEXP repairMeshSEXP, SEXP methodSEXP, SEXP ueRatioSEXP, SEXP ueCountSEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const bool >::type repairSoup(repairSoupSEXP);
    Rcpp::traits::input_parameter< const bool >::type repairMesh(repairMeshSEXP);
    Rcpp::traits::input_parameter< const Rcpp::String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const double >::type ueRatio(ueRatioSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type ueCount(ueCountSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(simplifyLT_cpp(rmesh, repairSoup, repairMesh, method, ueRatio, ueCount, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// simplifyGH_cpp
Rcpp::List simplifyGH_cpp(const Rcpp::List rmesh, const bool repairSoup, const bool repairMesh, const double ueRatio, const Rcpp::String policy, const bool normals, const bool verbose);
RcppExport SEXP _SurfaceMesh_simplifyGH_cpp(SEXP rmeshSEXP, SEXP repairSoupSEXP, SEXP repairMeshSEXP, SEXP ueRatioSEXP, SEXP policySEXP, SEXP normalsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const bool >::type repairSoup(repairSoupSEXP);
    Rcpp::traits::input_parameter< const bool >::type repairMesh(repairMeshSEXP);
    Rcpp::traits::input_parameter< const double >::type ueRatio(ueRatioSEXP);
    Rcpp::traits::input_parameter< const Rcpp::String >::type policy(policySEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(simplifyGH_cpp(rmesh, repairSoup, repairMesh, ueRatio, policy, normals, verbose));
    return rcpp_result_gen;
END_RCPP
}
// remeshSmoothShape_cpp
Rcpp::List remeshSmoothShape_cpp(const Rcpp::List rmesh, const Rcpp::IntegerVector indices, const unsigned int nIter, const double time, const bool normals);
RcppExport SEXP _SurfaceMesh_remeshSmoothShape_cpp(SEXP rmeshSEXP, SEXP indicesSEXP, SEXP nIterSEXP, SEXP timeSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(remeshSmoothShape_cpp(rmesh, indices, nIter, time, normals));
    return rcpp_result_gen;
END_RCPP
}
// remeshSmoothAA_cpp
Rcpp::List remeshSmoothAA_cpp(const Rcpp::List rmesh, const unsigned int nIter, const double dihedralAngle, const bool useAngleSmooth, const bool useAreaSmooth, const bool useSafeConstr, const bool useDelaunay, const bool doProject, const bool normals);
RcppExport SEXP _SurfaceMesh_remeshSmoothAA_cpp(SEXP rmeshSEXP, SEXP nIterSEXP, SEXP dihedralAngleSEXP, SEXP useAngleSmoothSEXP, SEXP useAreaSmoothSEXP, SEXP useSafeConstrSEXP, SEXP useDelaunaySEXP, SEXP doProjectSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const double >::type dihedralAngle(dihedralAngleSEXP);
    Rcpp::traits::input_parameter< const bool >::type useAngleSmooth(useAngleSmoothSEXP);
    Rcpp::traits::input_parameter< const bool >::type useAreaSmooth(useAreaSmoothSEXP);
    Rcpp::traits::input_parameter< const bool >::type useSafeConstr(useSafeConstrSEXP);
    Rcpp::traits::input_parameter< const bool >::type useDelaunay(useDelaunaySEXP);
    Rcpp::traits::input_parameter< const bool >::type doProject(doProjectSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(remeshSmoothAA_cpp(rmesh, nIter, dihedralAngle, useAngleSmooth, useAreaSmooth, useSafeConstr, useDelaunay, doProject, normals));
    return rcpp_result_gen;
END_RCPP
}
// remeshSmoothTR_cpp
Rcpp::List remeshSmoothTR_cpp(const Rcpp::List rmesh, const unsigned int nIter, const bool relaxConstr, const bool normals);
RcppExport SEXP _SurfaceMesh_remeshSmoothTR_cpp(SEXP rmeshSEXP, SEXP nIterSEXP, SEXP relaxConstrSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const bool >::type relaxConstr(relaxConstrSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(remeshSmoothTR_cpp(rmesh, nIter, relaxConstr, normals));
    return rcpp_result_gen;
END_RCPP
}
// subdivideCatmullClark_cpp
Rcpp::List subdivideCatmullClark_cpp(const Rcpp::List rmesh, const unsigned int nIter, const bool normals);
RcppExport SEXP _SurfaceMesh_subdivideCatmullClark_cpp(SEXP rmeshSEXP, SEXP nIterSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(subdivideCatmullClark_cpp(rmesh, nIter, normals));
    return rcpp_result_gen;
END_RCPP
}
// subdivideDooSabin_cpp
Rcpp::List subdivideDooSabin_cpp(const Rcpp::List rmesh, const unsigned int nIter, const bool triangulate, const bool normals);
RcppExport SEXP _SurfaceMesh_subdivideDooSabin_cpp(SEXP rmeshSEXP, SEXP nIterSEXP, SEXP triangulateSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate(triangulateSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(subdivideDooSabin_cpp(rmesh, nIter, triangulate, normals));
    return rcpp_result_gen;
END_RCPP
}
// subdivideSqrt3_cpp
Rcpp::List subdivideSqrt3_cpp(const Rcpp::List rmesh, const unsigned int nIter, const bool normals);
RcppExport SEXP _SurfaceMesh_subdivideSqrt3_cpp(SEXP rmeshSEXP, SEXP nIterSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(subdivideSqrt3_cpp(rmesh, nIter, normals));
    return rcpp_result_gen;
END_RCPP
}
// subdivideLoop_cpp
Rcpp::List subdivideLoop_cpp(const Rcpp::List rmesh, const unsigned int nIter, const bool normals);
RcppExport SEXP _SurfaceMesh_subdivideLoop_cpp(SEXP rmeshSEXP, SEXP nIterSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(subdivideLoop_cpp(rmesh, nIter, normals));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SurfaceMesh_alphaWrapPoints_cpp", (DL_FUNC) &_SurfaceMesh_alphaWrapPoints_cpp, 4},
    {"_SurfaceMesh_alphaWrapMesh_cpp", (DL_FUNC) &_SurfaceMesh_alphaWrapMesh_cpp, 4},
    {"_SurfaceMesh_boolIntersectionEK_cpp", (DL_FUNC) &_SurfaceMesh_boolIntersectionEK_cpp, 4},
    {"_SurfaceMesh_boolDifferenceEK_cpp", (DL_FUNC) &_SurfaceMesh_boolDifferenceEK_cpp, 5},
    {"_SurfaceMesh_boolUnionEK_cpp", (DL_FUNC) &_SurfaceMesh_boolUnionEK_cpp, 4},
    {"_SurfaceMesh_getJSCDSC_cpp", (DL_FUNC) &_SurfaceMesh_getJSCDSC_cpp, 3},
    {"_SurfaceMesh_getHausdorffApprox_cpp", (DL_FUNC) &_SurfaceMesh_getHausdorffApprox_cpp, 4},
    {"_SurfaceMesh_getHausdorffEst_cpp", (DL_FUNC) &_SurfaceMesh_getHausdorffEst_cpp, 4},
    {"_SurfaceMesh_getSurfaceDist_cpp", (DL_FUNC) &_SurfaceMesh_getSurfaceDist_cpp, 6},
    {"_SurfaceMesh_makeMesh_cpp", (DL_FUNC) &_SurfaceMesh_makeMesh_cpp, 10},
    {"_SurfaceMesh_makeMeshFF_cpp", (DL_FUNC) &_SurfaceMesh_makeMeshFF_cpp, 10},
    {"_SurfaceMesh_makeMeshValid_cpp", (DL_FUNC) &_SurfaceMesh_makeMeshValid_cpp, 5},
    {"_SurfaceMesh_makeMeshValidFF_cpp", (DL_FUNC) &_SurfaceMesh_makeMeshValidFF_cpp, 5},
    {"_SurfaceMesh_addVNormals_cpp", (DL_FUNC) &_SurfaceMesh_addVNormals_cpp, 1},
    {"_SurfaceMesh_doesBoundVolume_cpp", (DL_FUNC) &_SurfaceMesh_doesBoundVolume_cpp, 1},
    {"_SurfaceMesh_doesSelfIntersect_cpp", (DL_FUNC) &_SurfaceMesh_doesSelfIntersect_cpp, 1},
    {"_SurfaceMesh_fillBoundaryHoles_cpp", (DL_FUNC) &_SurfaceMesh_fillBoundaryHoles_cpp, 5},
    {"_SurfaceMesh_getArea_cpp", (DL_FUNC) &_SurfaceMesh_getArea_cpp, 1},
    {"_SurfaceMesh_getBoundingBox_cpp", (DL_FUNC) &_SurfaceMesh_getBoundingBox_cpp, 1},
    {"_SurfaceMesh_getBoundingBoxOptimal_cpp", (DL_FUNC) &_SurfaceMesh_getBoundingBoxOptimal_cpp, 3},
    {"_SurfaceMesh_getCentroid_cpp", (DL_FUNC) &_SurfaceMesh_getCentroid_cpp, 1},
    {"_SurfaceMesh_getConvexHull_cpp", (DL_FUNC) &_SurfaceMesh_getConvexHull_cpp, 2},
    {"_SurfaceMesh_getDistance_cpp", (DL_FUNC) &_SurfaceMesh_getDistance_cpp, 2},
    {"_SurfaceMesh_getVolume_cpp", (DL_FUNC) &_SurfaceMesh_getVolume_cpp, 1},
    {"_SurfaceMesh_hasGarbage_cpp", (DL_FUNC) &_SurfaceMesh_hasGarbage_cpp, 1},
    {"_SurfaceMesh_isClosed_cpp", (DL_FUNC) &_SurfaceMesh_isClosed_cpp, 1},
    {"_SurfaceMesh_isValid_cpp", (DL_FUNC) &_SurfaceMesh_isValid_cpp, 1},
    {"_SurfaceMesh_orientToBoundVolume_cpp", (DL_FUNC) &_SurfaceMesh_orientToBoundVolume_cpp, 2},
    {"_SurfaceMesh_removeSelfIntersections_cpp", (DL_FUNC) &_SurfaceMesh_removeSelfIntersections_cpp, 4},
    {"_SurfaceMesh_samplePoints_cpp", (DL_FUNC) &_SurfaceMesh_samplePoints_cpp, 2},
    {"_SurfaceMesh_triangulateMesh_cpp", (DL_FUNC) &_SurfaceMesh_triangulateMesh_cpp, 2},
    {"_SurfaceMesh_jet_pca_normals_cpp", (DL_FUNC) &_SurfaceMesh_jet_pca_normals_cpp, 3},
    {"_SurfaceMesh_readFileSoup_cpp", (DL_FUNC) &_SurfaceMesh_readFileSoup_cpp, 2},
    {"_SurfaceMesh_readFileMesh_cpp", (DL_FUNC) &_SurfaceMesh_readFileMesh_cpp, 3},
    {"_SurfaceMesh_writeFile_cpp", (DL_FUNC) &_SurfaceMesh_writeFile_cpp, 5},
    {"_SurfaceMesh_reconstructAFS_cpp", (DL_FUNC) &_SurfaceMesh_reconstructAFS_cpp, 4},
    {"_SurfaceMesh_reconstructPoisson_cpp", (DL_FUNC) &_SurfaceMesh_reconstructPoisson_cpp, 7},
    {"_SurfaceMesh_reconstructSSS_cpp", (DL_FUNC) &_SurfaceMesh_reconstructSSS_cpp, 9},
    {"_SurfaceMesh_remeshIsoUniform_cpp", (DL_FUNC) &_SurfaceMesh_remeshIsoUniform_cpp, 6},
    {"_SurfaceMesh_remeshIsoAdapt_cpp", (DL_FUNC) &_SurfaceMesh_remeshIsoAdapt_cpp, 8},
    {"_SurfaceMesh_simplifyLT_cpp", (DL_FUNC) &_SurfaceMesh_simplifyLT_cpp, 8},
    {"_SurfaceMesh_simplifyGH_cpp", (DL_FUNC) &_SurfaceMesh_simplifyGH_cpp, 7},
    {"_SurfaceMesh_remeshSmoothShape_cpp", (DL_FUNC) &_SurfaceMesh_remeshSmoothShape_cpp, 5},
    {"_SurfaceMesh_remeshSmoothAA_cpp", (DL_FUNC) &_SurfaceMesh_remeshSmoothAA_cpp, 9},
    {"_SurfaceMesh_remeshSmoothTR_cpp", (DL_FUNC) &_SurfaceMesh_remeshSmoothTR_cpp, 4},
    {"_SurfaceMesh_subdivideCatmullClark_cpp", (DL_FUNC) &_SurfaceMesh_subdivideCatmullClark_cpp, 3},
    {"_SurfaceMesh_subdivideDooSabin_cpp", (DL_FUNC) &_SurfaceMesh_subdivideDooSabin_cpp, 4},
    {"_SurfaceMesh_subdivideSqrt3_cpp", (DL_FUNC) &_SurfaceMesh_subdivideSqrt3_cpp, 3},
    {"_SurfaceMesh_subdivideLoop_cpp", (DL_FUNC) &_SurfaceMesh_subdivideLoop_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SurfaceMesh(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
