# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alphaWrapPoints_cpp <- function(pts, alpha_rel, offset_rel, normals) {
    .Call(`_SurfaceMesh_alphaWrapPoints_cpp`, pts, alpha_rel, offset_rel, normals)
}

alphaWrapMesh_cpp <- function(rmesh, alpha_rel, offset_rel, normals) {
    .Call(`_SurfaceMesh_alphaWrapMesh_cpp`, rmesh, alpha_rel, offset_rel, normals)
}

boolIntersectionEK_cpp <- function(rmeshes, repairSoup, normals, verbose) {
    .Call(`_SurfaceMesh_boolIntersectionEK_cpp`, rmeshes, repairSoup, normals, verbose)
}

boolDifferenceEK_cpp <- function(rmesh1, rmesh2, repairSoup, normals, verbose) {
    .Call(`_SurfaceMesh_boolDifferenceEK_cpp`, rmesh1, rmesh2, repairSoup, normals, verbose)
}

boolUnionEK_cpp <- function(rmeshes, repairSoup, normals, verbose) {
    .Call(`_SurfaceMesh_boolUnionEK_cpp`, rmeshes, repairSoup, normals, verbose)
}

getJSCDSC_cpp <- function(rmeshes, repairSoup, verbose) {
    .Call(`_SurfaceMesh_getJSCDSC_cpp`, rmeshes, repairSoup, verbose)
}

getHausdorffApprox_cpp <- function(rmesh1, rmesh2, symmetric, n) {
    .Call(`_SurfaceMesh_getHausdorffApprox_cpp`, rmesh1, rmesh2, symmetric, n)
}

getHausdorffEst_cpp <- function(rmesh1, rmesh2, symmetric, error_bound) {
    .Call(`_SurfaceMesh_getHausdorffEst_cpp`, rmesh1, rmesh2, symmetric, error_bound)
}

getSurfaceDist_cpp <- function(rmesh1, rmesh2, returnDists, symmetric, p, ropts) {
    .Call(`_SurfaceMesh_getSurfaceDist_cpp`, rmesh1, rmesh2, returnDists, symmetric, p, ropts)
}

makeMesh_cpp <- function(rmesh, triangulate, repairSoup, removeIntersections, removeMethod, fillHoles, fairHole, maxNumHoles, normals, verbose) {
    .Call(`_SurfaceMesh_makeMesh_cpp`, rmesh, triangulate, repairSoup, removeIntersections, removeMethod, fillHoles, fairHole, maxNumHoles, normals, verbose)
}

makeMeshFF_cpp <- function(filename, triangulate, repairSoup, removeIntersections, removeMethod, fillHoles, fairHole, maxNumHoles, normals, verbose) {
    .Call(`_SurfaceMesh_makeMeshFF_cpp`, filename, triangulate, repairSoup, removeIntersections, removeMethod, fillHoles, fairHole, maxNumHoles, normals, verbose)
}

makeMeshValid_cpp <- function(rmesh, soup, triangulate, normals, verbose) {
    .Call(`_SurfaceMesh_makeMeshValid_cpp`, rmesh, soup, triangulate, normals, verbose)
}

makeMeshValidFF_cpp <- function(filename, soup, triangulate, normals, verbose) {
    .Call(`_SurfaceMesh_makeMeshValidFF_cpp`, filename, soup, triangulate, normals, verbose)
}

addVNormals_cpp <- function(rmesh) {
    .Call(`_SurfaceMesh_addVNormals_cpp`, rmesh)
}

doesBoundVolume_cpp <- function(rmesh) {
    .Call(`_SurfaceMesh_doesBoundVolume_cpp`, rmesh)
}

doesSelfIntersect_cpp <- function(rmesh) {
    .Call(`_SurfaceMesh_doesSelfIntersect_cpp`, rmesh)
}

fillBoundaryHoles_cpp <- function(rmesh, fairHole, maxNumHoles, normals, verbose) {
    .Call(`_SurfaceMesh_fillBoundaryHoles_cpp`, rmesh, fairHole, maxNumHoles, normals, verbose)
}

getArea_cpp <- function(rmesh) {
    .Call(`_SurfaceMesh_getArea_cpp`, rmesh)
}

getBoundingBox_cpp <- function(rmesh) {
    .Call(`_SurfaceMesh_getBoundingBox_cpp`, rmesh)
}

getBoundingBoxOptimal_cpp <- function(rmeshIn, triangulate, normals) {
    .Call(`_SurfaceMesh_getBoundingBoxOptimal_cpp`, rmeshIn, triangulate, normals)
}

getCentroid_cpp <- function(rmesh) {
    .Call(`_SurfaceMesh_getCentroid_cpp`, rmesh)
}

getConvexHull_cpp <- function(rpoints, normals) {
    .Call(`_SurfaceMesh_getConvexHull_cpp`, rpoints, normals)
}

getDistance_cpp <- function(rmesh, rpoints) {
    .Call(`_SurfaceMesh_getDistance_cpp`, rmesh, rpoints)
}

getVolume_cpp <- function(rmesh) {
    .Call(`_SurfaceMesh_getVolume_cpp`, rmesh)
}

hasGarbage_cpp <- function(rmesh) {
    .Call(`_SurfaceMesh_hasGarbage_cpp`, rmesh)
}

isClosed_cpp <- function(rmesh) {
    .Call(`_SurfaceMesh_isClosed_cpp`, rmesh)
}

isValid_cpp <- function(rmesh) {
    .Call(`_SurfaceMesh_isValid_cpp`, rmesh)
}

orientToBoundVolume_cpp <- function(rmesh, normals) {
    .Call(`_SurfaceMesh_orientToBoundVolume_cpp`, rmesh, normals)
}

removeSelfIntersections_cpp <- function(rmesh, method, normals, verbose) {
    .Call(`_SurfaceMesh_removeSelfIntersections_cpp`, rmesh, method, normals, verbose)
}

samplePoints_cpp <- function(rmesh, ropts) {
    .Call(`_SurfaceMesh_samplePoints_cpp`, rmesh, ropts)
}

triangulateMesh_cpp <- function(rmesh, normals) {
    .Call(`_SurfaceMesh_triangulateMesh_cpp`, rmesh, normals)
}

jet_pca_normals_cpp <- function(pts, nbNeighbors, method) {
    .Call(`_SurfaceMesh_jet_pca_normals_cpp`, pts, nbNeighbors, method)
}

readFileSoup_cpp <- function(filename, verbose) {
    .Call(`_SurfaceMesh_readFileSoup_cpp`, filename, verbose)
}

readFileMesh_cpp <- function(filename, normals, verbose) {
    .Call(`_SurfaceMesh_readFileMesh_cpp`, filename, normals, verbose)
}

writeFile_cpp <- function(filename, binary, precision, vertices, faceList) {
    invisible(.Call(`_SurfaceMesh_writeFile_cpp`, filename, binary, precision, vertices, faceList))
}

reconstructAFS_cpp <- function(pts, nNeighbors, repairSoup, normals) {
    .Call(`_SurfaceMesh_reconstructAFS_cpp`, pts, nNeighbors, repairSoup, normals)
}

reconstructPoisson_cpp <- function(pts, normalsIn, spacing, smAngle, smRadius, smDistance, normals) {
    .Call(`_SurfaceMesh_reconstructPoisson_cpp`, pts, normalsIn, spacing, smAngle, smRadius, smDistance, normals)
}

reconstructSSS_cpp <- function(pts, scaleIterations, nNeighbors, nSamples, separateShells, forceManifold, borderAngle, repairSoup, normals) {
    .Call(`_SurfaceMesh_reconstructSSS_cpp`, pts, scaleIterations, nNeighbors, nSamples, separateShells, forceManifold, borderAngle, repairSoup, normals)
}

remeshIsoUniform_cpp <- function(rmesh, targetEdgeLen, nIter, nRelaxSteps, protectConstraints, normals) {
    .Call(`_SurfaceMesh_remeshIsoUniform_cpp`, rmesh, targetEdgeLen, nIter, nRelaxSteps, protectConstraints, normals)
}

remeshIsoAdapt_cpp <- function(rmesh, tol, edgeMin, edgeMax, nIter, nRelaxSteps, protectConstraints, normals) {
    .Call(`_SurfaceMesh_remeshIsoAdapt_cpp`, rmesh, tol, edgeMin, edgeMax, nIter, nRelaxSteps, protectConstraints, normals)
}

simplifyLT_cpp <- function(rmesh, repairSoup, repairMesh, method, ueRatio, ueCount, normals, verbose) {
    .Call(`_SurfaceMesh_simplifyLT_cpp`, rmesh, repairSoup, repairMesh, method, ueRatio, ueCount, normals, verbose)
}

simplifyGH_cpp <- function(rmesh, repairSoup, repairMesh, ueRatio, policy, normals, verbose) {
    .Call(`_SurfaceMesh_simplifyGH_cpp`, rmesh, repairSoup, repairMesh, ueRatio, policy, normals, verbose)
}

remeshSmoothShape_cpp <- function(rmesh, indices, nIter, time, normals) {
    .Call(`_SurfaceMesh_remeshSmoothShape_cpp`, rmesh, indices, nIter, time, normals)
}

remeshSmoothAA_cpp <- function(rmesh, dihedralAngle, nIter, useSafeConstr, doProject, normals) {
    .Call(`_SurfaceMesh_remeshSmoothAA_cpp`, rmesh, dihedralAngle, nIter, useSafeConstr, doProject, normals)
}

remeshSmoothTR_cpp <- function(rmesh, nIter, relaxConstr, normals) {
    .Call(`_SurfaceMesh_remeshSmoothTR_cpp`, rmesh, nIter, relaxConstr, normals)
}

subdivideCatmullClark_cpp <- function(rmesh, nIter, normals) {
    .Call(`_SurfaceMesh_subdivideCatmullClark_cpp`, rmesh, nIter, normals)
}

subdivideDooSabin_cpp <- function(rmesh, nIter, triangulate, normals) {
    .Call(`_SurfaceMesh_subdivideDooSabin_cpp`, rmesh, nIter, triangulate, normals)
}

subdivideSqrt3_cpp <- function(rmesh, nIter, normals) {
    .Call(`_SurfaceMesh_subdivideSqrt3_cpp`, rmesh, nIter, normals)
}

subdivideLoop_cpp <- function(rmesh, nIter, normals) {
    .Call(`_SurfaceMesh_subdivideLoop_cpp`, rmesh, nIter, normals)
}

